---

name: Container Image
on:
  push:
    branches:
      - master
  schedule:
    # Weekly on Sundays:
    - cron: '00 04 * * 0'

  workflow_dispatch:

jobs:

  container-focal:
    name: Update CI container images (Focal)
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'lanl/qmd-progress' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Focal Docker image
        uses: docker/build-push-action@v4
        id: docker_build_focal
        with:
          context: .
          file: Dockerfile-focal
          push: true
          tags: nicolasbock/qmd-progress:latest, nicolasbock/qmd-progress:focal
      - name: Image digest
        run: |
          echo "Focal image: ${{ steps.docker_build_focal.outputs.digest }}"

  container-jammy:
    name: Update CI container images (Jammy)
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'lanl/qmd-progress' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Jammy Docker image
        uses: docker/build-push-action@v4
        id: docker_build_jammy
        with:
          context: .
          file: Dockerfile-jammy
          push: true
          tags: nicolasbock/qmd-progress:jammy
      - name: Image digest
        run: |
          echo "Jammy image: ${{ steps.docker_build_jammy.outputs.digest }}"
